package com.hit.classservice.application.input_boundary.comment;

import com.hit.classservice.application.input.comment.CreateParentCommentForLessonStudentInput;
import com.hit.classservice.application.input_boundary.UseCase;
import com.hit.classservice.application.output.comment.CreateParentCommentForLessonStudentOutput;

public interface CreateParentCommentForLessonStudentDataCase extends UseCase<CreateParentCommentForLessonStudentInput, CreateParentCommentForLessonStudentOutput> {
}
